/**
 * Station → item IDs and search terms. Generated by buildStationMapping.js
 * Run: node scripts/exportMenuItemsForAnalysis.js && node scripts/exportStationsAndPresets.js && node scripts/buildStationMapping.js
 */

export const STATION_ITEM_IDS: Record<string, string[]> = {
  "All-American": ["rec5ISty68i5FHM0J","recELSGOhJcLZi8HR","recIqx2LXUxfPuw8b"],
  "All American Station": ["rec5ISty68i5FHM0J","recELSGOhJcLZi8HR","recIqx2LXUxfPuw8b"],
  "Build Your Own Sliders": ["recM7ld6ofcGyUWwj","recfetv3D3oelJQ4J","recodH0dXUWTwxgeV"],
  "BarWerx Appetizer Sampler": ["rec0MnkolhUFBvHF3","rec9xgfnkRzaqmMAo","recXnkMbxhY6UPhz9"],
  "Buffet – Full Pan (Hot)": ["reclK8bJGR88pjJGj"],
  "Carving Station": ["rec1KAz5OzhnxHCsw","recc7klJAfiFJJjY1"],
  "Chicken & Waffle Station": ["recbLOAHM6ot9neUF","recraQlpPw4Y3Eppp","recs1tfaD2q36tXyT"],
  "Dessert Station": ["rechtIIwbYPRAfLDU"],
  "Grande Charcuterie Display": ["rec0LRKQ4ZEhMSrm5","rec1fPcNdEAsBAe2U","rec4vGro0ynsGDH4a","rec5bNhFi0nX3yIw7","recA34aaW5YrL4FOW","recD0mXWQl594KFSn","recMbciITv1Hlbnru","recPapuuhnVFqCnWo","recQSqtB8kpZxPAYY","recQYNmJ7VtsAIvLA","recRtut4IxhKDlKJh","recbLOAHM6ot9neUF","recf9zxoQ81noHUba","recgj6cov8f0dOfUi","reciv37H0yQhh9ZnO","reckPad6B7kzAP8Pe","recnIL1TNRXndB4ps","recnX5QYSY0dnFVKO","recoQJJLZH0LRX5bu","recoaWN0x9lKcVoI3","recpt6f6oDrPDEo9l","recqdpAuyKl7Csx4K","recriA5em0ZNKiBRJ","rectKIGx2dlPhiuad","rectLW1RMUazCew0Q","rectt1OnDLqrP6DM0","recuhcXcbNVG4ELhd","recxl3acQZDyHsFB7","reczSQmQdIxe8J8NW"],
  "Grazing Station": ["recK7XryFFBjmS0nR","recOnZHDbvQT7wHby","recfgGpx8giizmoWC","recgY7zjTok92NLoA","reciv37H0yQhh9ZnO"],
  "Hi Bachi Station": ["rec0vi8lVP0SlMgLx","recOAmqGFpPhdjoI8","recQyBfaKKox5IzTn","recaO69ynwOgu1BOF"],
  "Iced Raw Bar": ["rec5antkMI1XPsu1m","rec6P5FirEH00FYv2","recLI7EGthBvwDHs2","recMbciITv1Hlbnru","recPbj1rc5GYao2n0","recQYNmJ7VtsAIvLA","recXvopIYzJSzahEW","reca4fukFNXNtqfpM","recgIKufYbIY9Gb15","rechGaAchTl8jfUAH","recrbblTU7ZZLc350","recuIQtAOiWtPByqV","recxCGVHiLrdBcZb3","reczRz4hJ0hse19wM"],
  "Make Your Own Ramen Noodle Bar": ["rec1OZMJPp5fzlaMs","rec8jECI7CUO0AYM4","recW6JGluwbCWr9CV","reclG7UrfTRLhQJbu","recyFMEFXxX7rftcW","reczPuBo8OnjpTWLW"],
  "Pasta Flight Presentation": ["rec3r2sr50gx6Q7FF","rec412OOQR5BXwE0Y"],
  "Pasta Station": ["rec3r2sr50gx6Q7FF","rec412OOQR5BXwE0Y","rec7A9eLBIdojfo0G","recM1xkQMGjZVe1rp","recXiGsnQD9ZHdBP2","recbJwOORXq3I5mBL","recgf22ZPDHALztAq"],
  "Slider Station": ["recM7ld6ofcGyUWwj","recfetv3D3oelJQ4J","recodH0dXUWTwxgeV"],
  "Station – Interactive": ["rec0e9S32difX0xcC","rec1z6eiptyMX58wk","rec3OwVCIAwO4Yk8n","rec52wKRUsO17T47g","rec8jECI7CUO0AYM4","recN3ekRt2motxVs8","recNCgbxnFu3ngRUK","recNjb9dkCReXHBS5","recPqaEPZnH2B7JBI","recRcMz6SA5RsK8yP","recW6JGluwbCWr9CV","recYqCUfHuMcRzbkR","recZSlU2Cz0LnfTEc","recfe7Ih79u2mf1NE","recg0cAEPqjsD95ks","recgu99XW9u8vVYoc","rechJdTiUNvGPTagz","reckhCulz7xRo0tY4","reclG7UrfTRLhQJbu","reclXBqCsImMSSWRq","reclgSifIretl5oyH","recn4nHezbBbRUApz","recprz1lR6dCZiAjC","recrUtTbdVtXORIeR","recvCdaL4g6N9UfWa","recyFMEFXxX7rftcW","reczOgCljesLYhIYD"],
  "Street Food Station": ["recgLpzG3dlOK6JaU","rectbVsioFIgmqCE3"],
  "Taco Station": ["recXmMxw2fcRjeGhh","recgu99XW9u8vVYoc"],
  "The Philly Jawn": ["rec2AssmNG9IqGXD2","rec3n7m6THzQRXBSo","rec6DDFHbv38ZVWfO","rec6KTM47QvZ9Krbn","rec80fAwLJ4osw9MB","recGG54Hp5FX2bmyh","recLY7BY02V6fL8em","recM7ld6ofcGyUWwj","recNCgbxnFu3ngRUK","recPQiYu0N5FEHqGi","recRlrWlqyaKkd6mq","recRnCBEHe1M2F2Rr","recVjVAz6zZPaBGWT","recXmMxw2fcRjeGhh","recXnkMbxhY6UPhz9","recbaXa2cnBKKBSu1","recfetv3D3oelJQ4J","recgN51fCfNjb0j4z","reclgSifIretl5oyH","recn4nHezbBbRUApz","recodH0dXUWTwxgeV","recvCdaL4g6N9UfWa","recw62l2NRdrqXSjE","recwpyjDNzgytj4Rg","reczOgCljesLYhIYD","reczPuBo8OnjpTWLW"],
  "Viva La Pasta": ["rec3r2sr50gx6Q7FF","rec412OOQR5BXwE0Y","rec7A9eLBIdojfo0G","recM1xkQMGjZVe1rp","recXiGsnQD9ZHdBP2","recbJwOORXq3I5mBL","recgf22ZPDHALztAq"],
};

export const STATION_ITEM_SEARCH_TERMS: Record<string, string[]> = {
  "All-American": ["potato wedges with white cheese –","potato","wedges","with","white","cheese","🍤 carolina pulled pork bites –","carolina","pulled","pork","bites","bbq pulled pork –"],
  "BarWerx Appetizer Sampler": ["mozzarella sticks – marinara sauce","mozzarella","sticks","marinara","sauce","🍤 buffalo bleu cheese quesadilla – bleu cheese dressing","buffalo","bleu","cheese","quesadilla","dressing","philly cheesy potato skins – sour cream","philly","cheesy","potato","skins","sour","cream"],
  "Buffet – Full Pan (Hot)": ["corncake –","corncake"],
  "Carving Station": ["roasted stuffed pork loin – fig & port wine reduction –","roasted","stuffed","pork","loin","port","wine","reduction","beef tenderloin carving station –","beef","tenderloin","carving","station"],
  "Chicken & Waffle Station": ["🍰 cinnamon sugar donut holes –","cinnamon","sugar","donut","holes","whipped cream –","whipped","cream","ice cream sundae bar – whipped cream, toppings, sauces","sundae","cream,","toppings,","sauces"],
  "Dessert Station": ["decadent dessert display –","decadent","dessert","display"],
  "Grande Charcuterie Display": ["🍤 fig & goat cheese crostini –","goat","cheese","crostini","grande charcuterie display –","grande","charcuterie","display","charcuterie sandwich –","sandwich","olives –","olives","herbed crostini –","herbed","whipped ricotta with crostini –","whipped","ricotta","with","coconut shrimp –","coconut","shrimp","chicken satay skewers – peanut dipping sauce","chicken","satay","skewers","peanut","dipping","sauce","🍽️ roasted turkey ballantine – charred plums, walnuts & parsnips –","roasted","turkey","ballantine","charred","plums,","walnuts","parsnips","🍤 firecracker shrimp –","firecracker","thai coconut curry chicken –","thai"],
  "Grazing Station": ["grazing table – appetizer / dessert hybrid","grazing","table","appetizer","dessert","hybrid","mediterranean mezze board –","mediterranean","mezze","board","antipasto platter –","antipasto","platter","seven-layer mediterranean dip –","seven-layer","mezze display – falafel, spanakopita, baba ghanoush, hummus, kalamata olives, couscous-stuffed peppers, pita","display","falafel,","spanakopita,","baba","ghanoush,","hummus,","kalamata","olives,","couscous-stuffed","peppers,","pita"],
  "Hi Bachi Station": ["🍽️ filet mignon au poivre –","filet","mignon","poivre","🍤 hibachi chicken kabobs –","hibachi","chicken","kabobs","🍽️ filet mignon au poivre – cognac peppercorn cream –","cognac","peppercorn","cream","tofu teriyaki –","tofu","teriyaki"],
  "Iced Raw Bar": ["🍽️ grilled denver steak – oyster mushrooms & demi –","grilled","denver","steak","oyster","mushrooms","demi","jumbo grilled and chilled shrimp –","jumbo","chilled","shrimp","shrimp scampi (buffet) –","scampi","(buffet)","coconut shrimp –","coconut","potato-wrapped shrimp –","potato-wrapped","🍤 firecracker shrimp –","firecracker","🍽️ shrimp & grits – cajun holy trinity –","grits","cajun","holy","trinity","cajun shrimp & grit bites – creole cream sauce","grit","bites","creole","cream","sauce","shrimp & grits (buffet) –","shrimp scampi –","🍽️ shrimp scampi – garlic, butter & white wine linguine –","garlic,","butter","white","wine","linguine","shrimp cocktail platter –"],
  "Make Your Own Ramen Noodle Bar": ["🧀 ramen station –","ramen","station","traditional ramen broth –","traditional","broth","ramen noodles –","noodles","miso ramen broth –","miso","soft boiled eggs –","soft","boiled","eggs","🍤 sriracha chicken meatballs –","sriracha","chicken","meatballs"],
  "Pasta Flight Presentation": ["🥗 bowties primavera –","bowties","primavera","🥗 penne a la vodka –","penne","vodka"],
  "Pasta Station": ["🥗 bowties primavera –","bowties","primavera","🥗 penne a la vodka –","penne","vodka","penne vodka –","penne à la vodka –","penne primavera –"],
  "Slider Station": ["philly jawn – sandwich station –","philly","jawn","sandwich","station","assorted slider rolls –","assorted","slider","rolls","build your own cheesesteaks station –","build","your","cheesesteaks"],
  "Station – Interactive": ["provolone cheese –","provolone","cheese","sautéed peppers & onions –","sautéed","peppers","onions","scallions –","scallions","crispy onion strings –","crispy","onion","strings","traditional ramen broth –","traditional","ramen","broth","grilled chicken –","grilled","chicken","philly roast pork –","philly","roast","pork","protein toppings (pork/chicken/tofu) –","protein","toppings","(pork/chicken/tofu)","buffalo chicken –","buffalo","vegetable toppings –","vegetable","ramen noodles –","noodles","lobster mac & cheese –","lobster","four cheese mac & cheese –","four","pickled jalapeños –","pickled"],
  "Street Food Station": ["korean bbq pork bao bun – crunchy slaw","korean","pork","crunchy","slaw","🥤 signature cocktails – margarita, mocktail bases","signature","cocktails","margarita,","mocktail","bases"],
  "Taco Station": ["🧀 street food station – fish tacos, sliders, mac & cheese","street","food","station","fish","tacos,","sliders,","cheese","fish tacos –","tacos"],
  "The Philly Jawn": ["cheesesteak dumplings – spicy ketchup","cheesesteak","dumplings","spicy","ketchup","south philly roast pork – provolone & broccoli rabe –","south","philly","roast","pork","provolone","broccoli","rabe","🍽️ philly roast pork – provolone","🍰 philly soft pretzels – cheese & mustard","soft","pretzels","cheese","mustard","sliders / panini –","sliders","panini","🍰 pretzel nuggets – chocolate buttercream","pretzel","nuggets","chocolate","buttercream","🍽️ chicken cheesesteaks –","chicken","cheesesteaks","philly jawn – sandwich station –","jawn","sandwich","station","philly roast pork –","south philly roast pork (buffet) –","(buffet)","angus beef sliders –","angus","beef"],
  "Viva La Pasta": ["🥗 bowties primavera –","bowties","primavera","🥗 penne a la vodka –","penne","vodka","penne vodka –","penne à la vodka –","penne primavera –"],
};

export function hasStationMapping(stationType: string): boolean {
  return (STATION_ITEM_IDS[stationType]?.length ?? 0) > 0 || (STATION_ITEM_SEARCH_TERMS[stationType]?.length ?? 0) > 0;
}

export function getStationItemIds(stationType: string): string[] {
  return STATION_ITEM_IDS[stationType] ?? [];
}

/** Instruction shown to user (e.g. "Choose 2", "Pick 2 pastas"). */
export const STATION_INSTRUCTIONS: Record<string, string> = {
  "Viva La Pasta": "Pick 2 pastas",
  "Pasta Station": "Pick 2 pastas",
  "Pasta Flight Presentation": "All 3 pastas",
  "Tex-Mex": "Choose 2 proteins",
  "Taco Station": "Choose 2 proteins",
  "Carving Station": "Choose 2",
  "Hi Bachi Station": "Choose 2",
  "Street Food Station": "Choose 5",
  "BarWerx Appetizer Sampler": "Choose 4",
  "The Philly Jawn": "Choose 4",
  "Iced Raw Bar": "Choose 1",
  "Grande Charcuterie Display": "Choose 1",
  "All-American": "Choose items",
  "All American Station": "Choose items",
  "Build Your Own Sliders": "Choose slider items",
  "Slider Station": "Choose slider items",
  "Make Your Own Ramen Noodle Bar": "Build your own",
  "Chicken & Waffle Station": "Choose items",
};

/** Max items to select (e.g. 2 for "Choose 2"). 0 = no limit. */
export const STATION_PICK_COUNT: Record<string, number> = {
  "Viva La Pasta": 2,
  "Pasta Station": 2,
  "Pasta Flight Presentation": 3,
  "Tex-Mex": 2,
  "Taco Station": 2,
  "Carving Station": 2,
  "Hi Bachi Station": 2,
  "Street Food Station": 5,
  "BarWerx Appetizer Sampler": 4,
  "The Philly Jawn": 4,
  "Iced Raw Bar": 1,
  "Grande Charcuterie Display": 1,
  "All-American": 0,
  "All American Station": 0,
  "Build Your Own Sliders": 0,
  "Slider Station": 0,
  "Make Your Own Ramen Noodle Bar": 0,
  "Chicken & Waffle Station": 0,
};

export function itemMatchesStation(itemName: string, stationType: string): boolean {
  const terms = STATION_ITEM_SEARCH_TERMS[stationType];
  if (!terms?.length) return false;
  const lower = itemName.toLowerCase();
  return terms.some((t) => lower.includes(t.toLowerCase()));
}

/** Viva La Pasta: pasta choices (pick 2) — pre-made as entree options. */
export const VIVA_LA_PASTA_PASTAS = ["Bowtie pasta", "Cheese tortellini", "Capellini", "Ziti", "Penne"] as const;

/** Viva La Pasta: default toppings — populate like serviceware; client may remove/add. */
export const VIVA_LA_PASTA_DEFAULT_TOPPINGS = [
  "Mushrooms",
  "Broccoli",
  "Olives",
  "Tomatoes",
  "Spinach",
  "Parmesan Cheese",
  "Bacon",
  "Sausage",
  "Chicken",
  "Shrimp",
] as const;

/** Viva La Pasta: sauces (placeholder — user will provide list later). */
export const VIVA_LA_PASTA_SAUCES: readonly string[] = [];

/** Station types that use a custom UI instead of Auto Populate. */
export const STATIONS_WITH_CUSTOM_UI: string[] = ["Viva La Pasta"];