import { FIELD_IDS } from '../services/airtable/events';

export const BEO_EVENTS = {
  // ── Client (Contract Holder) ──
  CLIENT_FIRST_NAME: FIELD_IDS.CLIENT_FIRST_NAME,
  CLIENT_LAST_NAME: FIELD_IDS.CLIENT_LAST_NAME,
  CLIENT_PHONE: FIELD_IDS.CLIENT_PHONE,

  // ── Primary Contact (Day-Of Person) ──
  CONTACT_FIRST_NAME: 'fld9LnsDlMBTl7C1G',
  CONTACT_LAST_NAME: FIELD_IDS.PRIMARY_CONTACT_NAME,
  CONTACT_PHONE: FIELD_IDS.PRIMARY_CONTACT_PHONE,

  // ── Venue ──
  VENUE_NAME: FIELD_IDS.VENUE_NAME,
  VENUE_ADDRESS: 'fldtCOxi4Axjfjt0V',
  VENUE_CITY: FIELD_IDS.VENUE_CITY,
  VENUE_STATE: FIELD_IDS.VENUE_STATE,
  VENUE_FULL_ADDRESS_CLEAN: FIELD_IDS.VENUE_ADDRESS,

  // ── Final Print Location (Computed) ──
  EVENT_LOCATION_FINAL_PRINT: 'flddestyZNoX9sKGE',

  // ── Event Times ──
  EVENT_START_TIME: FIELD_IDS.EVENT_START_TIME,
  EVENT_END_TIME: FIELD_IDS.EVENT_END_TIME,
  DISPATCH_TIME: FIELD_IDS.DISPATCH_TIME,

  // ── Event Details ──
  EVENT_DATE: FIELD_IDS.EVENT_DATE,
  GUEST_COUNT: FIELD_IDS.GUEST_COUNT,
  DIETARY_NOTES: FIELD_IDS.DIETARY_NOTES,
  SERVICE_STYLE: FIELD_IDS.SERVICE_STYLE,

  // ── Menu Sections ──
  PASSED_APPETIZERS: FIELD_IDS.PASSED_APPETIZERS,
  PRESENTED_APPETIZERS: FIELD_IDS.PRESENTED_APPETIZERS,
  BUFFET_METAL: FIELD_IDS.BUFFET_METAL,
  BUFFET_CHINA: FIELD_IDS.BUFFET_CHINA,
  DESSERTS: FIELD_IDS.DESSERTS,
  BEVERAGES: FIELD_IDS.BEVERAGES,
  STATIONS: 'fldbbDlpheiUGQbKu',
} as const;

export const BEO_MENU_ITEM_FIELDS = {
  LOADED: 'fldrKmicpgzVJRGjp', // Checkbox for Expeditor View
} as const;
